import sys, recolha_de_lixo, re
def sair(modo):
    if modo == 0:
        recolha_de_lixo.código()
        sys.exit(0)
    elif modo == 1:
        print("Something has gone wrong.")
        recolha_de_lixo.código()
        sys.exit(1)
def listarISO639_1Semobsoletos():
    #ISO 639-1, sem códigos obsoletos.
    return {
    "Afar": "aa",
    "Abecásio": "ab",
    "Avestã": "ae",
    "Africâner": "af",
    "Akan": "ak",
    "Amárico": "am",
    "Aragonês": "an",
    "Árabe": "ar",
    "Assamês": "as",
    "Ávaro": "av",
    "Aimará": "ay",
    "Azeri": "az",
    "Bashkir": "ba",
    "Bielorrusso": "be",
    "Búlgaro": "bg",
    "Biari": "bh",
    "Bislama": "bi",
    "Bambara": "bm",
    "Bengali": "bn",
    "Tibetano": "bo",
    "Bretão": "br",
    "Bósnio": "bs",
    "Catalão": "ca",
    "Checheno": "ce",
    "Chamorro": "ch",
    "Córsego": "co",
    "Cree": "cr",
    "Tcheco": "cs",
    "Eslavo Eclesiástico": "cu",
    "Chuvache": "cv",
    "Galês": "cy",
    "Dinamarquês": "da",
    "Alemão": "de",
    "Divehi": "dv",
    "Dzongkha": "dz",
    "Eve": "ee",
    "Grego": "el",
    "Inglês": "en",
    "Esperanto": "eo",
    "Espanhol": "es",
    "Estoniano": "et",
    "Basco": "eu",
    "Persa": "fa",
    "Fula": "ff",
    "Finlandês": "fi",
    "Fijiano": "fj",
    "Feroês": "fo",
    "Francês": "fr",
    "Frísio": "fy",
    "Irlandês": "ga",
    "Gaélico Escocês": "gd",
    "Galego": "gl",
    "Guarani": "gn",
    "Guzerate": "gu",
    "Manx": "gv",
    "Hauçá": "ha",
    "Hebraico": "he",
    "Hindi": "hi",
    "Hiri Motu": "ho",
    "Croata": "hr",
    "Haitiano": "ht",
    "Húngaro": "hu",
    "Armênio": "hy",
    "Herero": "hz",
    "Interlíngua": "ia",
    "Indonésio": "id",
    "Interlingue": "ie",
    "Igbo": "ig",
    "Sichuan Yi": "ii",
    "Inupiaque": "ik",
    "Ido": "io",
    "Islandês": "is",
    "Italiano": "it",
    "Inuktitut": "iu",
    "Japonês": "ja",
    "Javanês": "jv",
    "Georgiano": "ka",
    "Congo": "kg",
    "Quicuio": "ki",
    "Cuanhama": "kj",
    "Cazaque": "kk",
    "Groenlandês": "kl",
    "Khmer": "km",
    "Canarim": "kn",
    "Coreano": "ko",
    "Canúri": "kr",
    "Caxemira": "ks",
    "Curdo": "ku",
    "Komi": "kv",
    "Córnico": "kw",
    "Quirguiz": "ky",
    "Latim": "la",
    "Luxemburguês": "lb",
    "Luganda": "lg",
    "Limburguês": "li",
    "Lingala": "ln",
    "Laosiano": "lo",
    "Lituano": "lt",
    "Luba-Katanga": "lu",
    "Letão": "lv",
    "Malgaxe": "mg",
    "Marshallês": "mh",
    "Maori": "mi",
    "Macedônio": "mk",
    "Malaiala": "ml",
    "Mongol": "mn",
    "Marata": "mr",
    "Malaio": "ms",
    "Maltês": "mt",
    "Birmanês": "my",
    "Nauruano": "na",
    "Norueguês Bokmål": "nb",
    "Ndebele do Norte": "nd",
    "Nepalês": "ne",
    "Ndonga": "ng",
    "Holandês": "nl",
    "Norueguês Nynorsk": "nn",
    "Norueguês": "no",
    "Ndebele do Sul": "nr",
    "Navajo": "nv",
    "Nianja": "ny",
    "Occitânico": "oc",
    "Ojibwa": "oj",
    "Oromo": "om",
    "Oriá": "or",
    "Osseto": "os",
    "Panjabi": "pa",
    "Pali": "pi",
    "Polonês": "pl",
    "Pastó": "ps",
    "Português": "pt",
    "Quíchua": "qu",
    "Romanche": "rm",
    "Kirundi": "rn",
    "Romeno": "ro",
    "Russo": "ru",
    "Quiniaruanda": "rw",
    "Sânscrito": "sa",
    "Sardo": "sc",
    "Sindi": "sd",
    "Sami do Norte": "se",
    "Sango": "sg",
    "Cingalês": "si",
    "Eslovaco": "sk",
    "Esloveno": "sl",
    "Samoano": "sm",
    "Shona": "sn",
    "Somali": "so",
    "Albanês": "sq",
    "Sérvio": "sr",
    "Suázi": "ss",
    "Sesoto": "st",
    "Sundanês": "su",
    "Sueco": "sv",
    "Suaíli": "sw",
    "Tâmil": "ta",
    "Telugo": "te",
    "Tajique": "tg",
    "Tailandês": "th",
    "Tigrínia": "ti",
    "Turcomeno": "tk",
    "Tagalo": "tl",
    "Setsuana": "tn",
    "Tonga": "to",
    "Turco": "tr",
    "Tsonga": "ts",
    "Tatar": "tt",
    "Twi": "tw",
    "Taitiano": "ty",
    "Uigur": "ug",
    "Ucraniano": "uk",
    "Urdu": "ur",
    "Uzbeque": "uz",
    "Venda": "ve",
    "Vietnamita": "vi",
    "Volapuque": "vo",
    "Valão": "wa",
    "Wolof": "wo",
    "Xhosa": "xh",
    "Iídiche": "yi",
    "Iorubá": "yo",
    "Zhuang": "za",
    "Chinês": "zh",
    "Zulu": "zu"
    }
def listarISO3166_1alpha_2Semobsoletos():
    return {
        "Afeganistão": "AF",
    "África do Sul": "ZA",
    "Albânia": "AL",
    "Alemanha": "DE",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antártida": "AQ",
    "Antígua e Barbuda": "AG",
    "Arábia Saudita": "SA",
    "Argélia": "DZ",
    "Argentina": "AR",
    "Armênia": "AM",
    "Aruba": "AW",
    "Austrália": "AU",
    "Áustria": "AT",
    "Azerbaijão": "AZ",
    "Bahamas": "BS",
    "Bahrein": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Bélgica": "BE",
    "Belize": "BZ",
    "Benim": "BJ",
    "Bermudas": "BM",
    "Bielorrússia": "BY",
    "Bolívia": "BO",
    "Bonaire, Santo Eustáquio e Saba": "BQ",
    "Bósnia e Herzegovina": "BA",
    "Botsuana": "BW",
    "Brasil": "BR",
    "Brunei": "BN",
    "Bulgária": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Butão": "BT",
    "Cabo Verde": "CV",
    "Camarões": "CM",
    "Camboja": "KH",
    "Canadá": "CA",
    "Catar": "QA",
    "Cazaquistão": "KZ",
    "Chade": "TD",
    "Chile": "CL",
    "China": "CN",
    "Chipre": "CY",
    "Colômbia": "CO",
    "Comores": "KM",
    "Congo-Brazzaville": "CG",
    "Congo-Kinshasa": "CD",
    "Coreia do Norte": "KP",
    "Coreia do Sul": "KR",
    "Costa do Marfim": "CI",
    "Costa Rica": "CR",
    "Croácia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Dinamarca": "DK",
    "Djibuti": "DJ",
    "Dominica": "DM",
    "Egito": "EG",
    "El Salvador": "SV",
    "Emirados Árabes Unidos": "AE",
    "Equador": "EC",
    "Eritreia": "ER",
    "Eslováquia": "SK",
    "Eslovênia": "SI",
    "Espanha": "ES",
    "Estados Unidos": "US",
    "Estônia": "EE",
    "Eswatini": "SZ",
    "Etiópia": "ET",
    "Fiji": "FJ",
    "Filipinas": "PH",
    "Finlândia": "FI",
    "França": "FR",
    "Gabão": "GA",
    "Gâmbia": "GM",
    "Gana": "GH",
    "Geórgia": "GE",
    "Gibraltar": "GI",
    "Granada": "GD",
    "Grécia": "GR",
    "Groenlândia": "GL",
    "Guadalupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guiana": "GY",
    "Guiana Francesa": "GF",
    "Guiné": "GN",
    "Guiné-Bissau": "GW",
    "Guiné Equatorial": "GQ",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungria": "HU",
    "Iêmen": "YE",
    "Ilha Bouvet": "BV",
    "Ilha Christmas": "CX",
    "Ilha de Man": "IM",
    "Ilha Norfolk": "NF",
    "Ilhas Aland": "AX",
    "Ilhas Cayman": "KY",
    "Ilhas Cocos (Keeling)": "CC",
    "Ilhas Cook": "CK",
    "Ilhas Faroé": "FO",
    "Ilhas Geórgia do Sul e Sandwich do Sul": "GS",
    "Ilhas Heard e McDonald": "HM",
    "Ilhas Malvinas": "FK",
    "Ilhas Marianas do Norte": "MP",
    "Ilhas Marshall": "MH",
    "Ilhas Menores Distantes dos Estados Unidos": "UM",
    "Ilhas Salomão": "SB",
    "Ilhas Turks e Caicos": "TC",
    "Ilhas Virgens Americanas": "VI",
    "Ilhas Virgens Britânicas": "VG",
    "Índia": "IN",
    "Indonésia": "ID",
    "Irã": "IR",
    "Iraque": "IQ",
    "Irlanda": "IE",
    "Islândia": "IS",
    "Israel": "IL",
    "Itália": "IT",
    "Jamaica": "JM",
    "Japão": "JP",
    "Jersey": "JE",
    "Jordânia": "JO",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Laos": "LA",
    "Lesoto": "LS",
    "Letônia": "LV",
    "Líbano": "LB",
    "Libéria": "LR",
    "Líbia": "LY",
    "Liechtenstein": "LI",
    "Lituânia": "LT",
    "Luxemburgo": "LU",
    "Macau": "MO",
    "Macedônia do Norte": "MK",
    "Madagascar": "MG",
    "Malásia": "MY",
    "Malaui": "MW",
    "Maldivas": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marrocos": "MA",
    "Martinica": "MQ",
    "Maurício": "MU",
    "Mauritânia": "MR",
    "Mayotte": "YT",
    "México": "MX",
    "Mianmar": "MM",
    "Micronésia": "FM",
    "Moçambique": "MZ",
    "Moldávia": "MD",
    "Mônaco": "MC",
    "Mongólia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Namíbia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Nicarágua": "NI",
    "Níger": "NE",
    "Nigéria": "NG",
    "Niue": "NU",
    "Noruega": "NO",
    "Nova Caledônia": "NC",
    "Nova Zelândia": "NZ",
    "Omã": "OM",
    "Países Baixos": "NL",
    "Palau": "PW",
    "Palestina": "PS",
    "Panamá": "PA",
    "Papua-Nova Guiné": "PG",
    "Paquistão": "PK",
    "Paraguai": "PY",
    "Peru": "PE",
    "Polinésia Francesa": "PF",
    "Polônia": "PL",
    "Porto Rico": "PR",
    "Portugal": "PT",
    "Principado de Mônaco": "MC",
    "Quênia": "KE",
    "Quirguistão": "KG",
    "Reino Unido": "GB",
    "República Centro-Africana": "CF",
    "República Checa": "CZ",
    "República Dominicana": "DO",
    "Reunião": "RE",
    "Romênia": "RO",
    "Ruanda": "RW",
    "Rússia": "RU",
    "Saara Ocidental": "EH",
    "Samoa": "WS",
    "Samoa Americana": "AS",
    "San Marino": "SM",
    "Santa Helena": "SH",
    "Santa Lúcia": "LC",
    "São Bartolomeu": "BL",
    "São Cristóvão e Névis": "KN",
    "São Martinho (França)": "MF",
    "São Martinho (Países Baixos)": "SX",
    "São Pedro e Miquelão": "PM",
    "São Tomé e Príncipe": "ST",
    "São Vicente e Granadinas": "VC",
    "Seicheles": "SC",
    "Senegal": "SN",
    "Serra Leoa": "SL",
    "Sérvia": "RS",
    "Singapura": "SG",
    "Síria": "SY",
    "Somália": "SO",
    "Sri Lanka": "LK",
    "Sudão": "SD",
    "Sudão do Sul": "SS",
    "Suécia": "SE",
    "Suíça": "CH",
    "Suriname": "SR",
    "Svalbard e Jan Mayen": "SJ",
    "Tailândia": "TH",
    "Taiwan": "TW",
    "Tajiquistão": "TJ",
    "Tanzânia": "TZ",
    "Território Britânico do Oceano Índico": "IO",
    "Territórios Franceses do Sul": "TF",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad e Tobago": "TT",
    "Tunísia": "TN",
    "Turcomenistão": "TM",
    "Turquia": "TR",
    "Tuvalu": "TV",
    "Ucrânia": "UA",
    "Uganda": "UG",
    "Uruguai": "UY",
    "Uzbequistão": "UZ",
    "Vanuatu": "VU",
    "Vaticano": "VA",
    "Venezuela": "VE",
    "Vietnã": "VN",
    "Wallis e Futuna": "WF",
    "Zâmbia": "ZM",
    "Zimbábue": "ZW"
    }
def listarISO15924Semobsoletos():
    return {
        "Latino": "Latn",
        "Cirílico": "Cyrl",
        "Grego": "Grek",
        "Chinês Simplificado": "Hans",
        "Chinês Tradicional": "Hant",
        "Japonês": "Jpan",
        "Hiragana": "Hira",
        "Katakana": "Kana",
        "Hangul": "Hang",
        "Árabe": "Arab",
        "Hebraico": "Hebr",
        "Thaana": "Thaa",
        "Devanagari": "Deva",
        "Tailandês": "Thai",
        "Bengali": "Beng",
        "Guzerate": "Gujr",
        "Tâmil": "Taml",
        "Khmer": "Khmr"
    }
def listarUN_M49():
    return {
        "Afeganistão": "004",
        "África do Sul": "710",
        "Albânia": "008",
        "Alemanha": "276",
        "Andorra": "020",
        "Angola": "024",
        "Antígua e Barbuda": "028",
        "Arábia Saudita": "682",
        "Argélia": "012",
        "Argentina": "032",
        "Armênia": "051",
        "Austrália": "036",
        "Áustria": "040",
        "Azerbaijão": "031",
        "Bahamas": "044",
        "Bangladesh": "050",
        "Barbados": "052",
        "Bahrein": "048",
        "Bélgica": "056",
        "Belize": "084",
        "Benim": "204",
        "Bermudas": "060",
        "Bielorrússia": "112",
        "Bolívia": "068",
        "Bósnia e Herzegovina": "070",
        "Botsuana": "072",
        "Brasil": "076",
        "Brunei Darussalam": "096",
        "Bulgária": "100",
        "Burquina Faso": "854",
        "Burundi": "108",
        "Butão": "064",
        "Cabo Verde": "132",
        "Camarões": "120",
        "Camboja": "116",
        "Canadá": "124",
        "Catar": "634",
        "Cazaquistão": "398",
        "Chade": "148",
        "Chile": "152",
        "China": "156",
        "Chipre": "196",
        "Colômbia": "170",
        "Comores": "174",
        "Congo": "178",
        "Coreia do Norte": "408",
        "Coreia do Sul": "410",
        "Costa do Marfim": "384",
        "Costa Rica": "188",
        "Croácia": "191",
        "Cuba": "192",
        "Dinamarca": "208",
        "Djibuti": "262",
        "Dominica": "212",
        "Egito": "818",
        "El Salvador": "222",
        "Emirados Árabes Unidos": "784",
        "Equador": "218",
        "Eritreia": "232",
        "Eslováquia": "703",
        "Eslovênia": "705",
        "Espanha": "724",
        "Estados Unidos": "840",
        "Estônia": "233",
        "Eswatini": "748",
        "Etiópia": "231",
        "Fiji": "242",
        "Filipinas": "608",
        "Finlândia": "246",
        "França": "250",
        "Gabão": "266",
        "Gâmbia": "270",
        "Gana": "288",
        "Geórgia": "268",
        "Granada": "308",
        "Grécia": "300",
        "Guatemala": "320",
        "Guiana": "328",
        "Guiné": "324",
        "Guiné Equatorial": "226",
        "Guiné-Bissau": "624",
        "Haiti": "332",
        "Honduras": "340",
        "Hungria": "348",
        "Iêmen": "887",
        "Índia": "356",
        "Indonésia": "360",
        "Irã": "364",
        "Iraque": "368",
        "Irlanda": "372",
        "Islândia": "352",
        "Israel": "376",
        "Itália": "380",
        "Jamaica": "388",
        "Japão": "392",
        "Jordânia": "400",
        "Kuwait": "414",
        "Laos": "418",
        "Lesoto": "426",
        "Letônia": "428",
        "Líbano": "422",
        "Libéria": "430",
        "Líbia": "434",
        "Liechtenstein": "438",
        "Lituânia": "440",
        "Luxemburgo": "442",
        "Madagascar": "450",
        "Malásia": "458",
        "Malaui": "454",
        "Maldivas": "462",
        "Mali": "466",
        "Malta": "470",
        "Marrocos": "504",
        "Maurícia": "480",
        "Mauritânia": "478",
        "México": "484",
        "Mianmar": "104",
        "Micronésia": "583",
        "Moçambique": "508",
        "Moldávia": "498",
        "Mônaco": "492",
        "Mongólia": "496",
        "Montenegro": "499",
        "Namíbia": "516",
        "Nauru": "520",
        "Nepal": "524",
        "Nicarágua": "558",
        "Níger": "562",
        "Nigéria": "566",
        "Noruega": "578",
        "Nova Zelândia": "554",
        "Omã": "512",
        "Países Baixos": "528",
        "Palau": "585",
        "Panamá": "591",
        "Papua Nova Guiné": "598",
        "Paquistão": "586",
        "Paraguai": "600",
        "Peru": "604",
        "Polônia": "616",
        "Portugal": "620",
        "Quênia": "404",
        "Quirguistão": "417",
        "Reino Unido": "826",
        "República Centro-Africana": "140",
        "República Checa": "203",
        "República Democrática do Congo": "180",
        "República Dominicana": "214",
        "Romênia": "642",
        "Ruanda": "646",
        "Rússia": "643",
        "Samoa": "882",
        "San Marino": "674",
        "Santa Lúcia": "662",
        "São Cristóvão e Neves": "659",
        "São Tomé e Príncipe": "678",
        "São Vicente e Granadinas": "670",
        "Senegal": "686",
        "Serra Leoa": "694",
        "Sérvia": "688",
        "Seychelles": "690",
        "Singapura": "702",
        "Síria": "760",
        "Somália": "706",
        "Sri Lanka": "144",
        "Sudão": "729",
        "Sudão do Sul": "728",
        "Suécia": "752",
        "Suíça": "756",
        "Suriname": "740",
        "Tailândia": "764",
        "Tajiquistão": "762",
        "Tanzânia": "834",
        "Timor-Leste": "626",
        "Togo": "768",
        "Tonga": "776",
        "Trindade e Tobago": "780",
        "Tunísia": "788",
        "Turquemenistão": "795",
        "Turquia": "792",
        "Tuvalu": "798",
        "Ucrânia": "804",
        "Uganda": "800",
        "Uruguai": "858",
        "Uzbequistão": "860",
        "Vanuatu": "548",
        "Venezuela": "862",
        "Vietnã": "704",
        "Zâmbia": "894",
        "Zimbábue": "716"
    }